### ISSUE TITLE
Freezes once, in Chrome, after first transition

### ISSUE THREAD

**Issue by nwhiteley** [buildinternet/totem#3] opened 2011-06-07 18:25 UTC
Hi,

On first loading of a page containg a "totem" list, the list freezes after the first transition.

After any kind of interaction with the page or the "totem" list, the list functions as normal until the page is again loaded for the first time.

A page refresh will not replicate the issue. The page must be newly loaded.

Google Chrome Version: 11.0.696.77

Neil

**Comment by zachdunn** [comment] 2011-06-08 19:30
I'm having a hard time replicating the issue. Especially since it appears to work on page reloads, I'm wondering if there was a  hiccup with the Google-hosted jQuery? If anyone else can confirm this issue, I'll take another look. Closing in the meantime.

**Closed as completed by zachdunn** 2011-06-08 19:30 UTC
Labels: Compatibility

**Comment by nwhiteley** [comment] 2011-06-08 21:00
Use the Demo page.
If you navigate to the page in any way it doesn't happen.

Open Chrome. Enter the url of the demo page in to the address bar and hit enter.

It's not a demo page thing, it happens on any page but only if you enter the page directly and it's only Google Chrome that does it.

**Comment by zachdunn** [comment] 2011-06-13 20:25
Just tried this myself, and I can't for the life of me reproduce what you're having an issue with. Given the circumstances in which it works/doesn't work, I don't know if I can assign blame to this specific script as it seems to be a bug with the browser itself. Type of page load shouldn't have any bearing on the JavaScript like this.
